// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostagemFacil.Solicitacoes.API.Data;

#nullable disable

namespace PostagemFacil.Solicitacoes.API.Data.Migrations
{
    [DbContext(typeof(SolictacoesContext))]
    [Migration("20230610182312_SeedTables")]
    partial class SeedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PostagemFacil.Solicitacoes.API.Data.Models.PesoLimite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PesoLimite");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Até 3kg"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Entre 3kg e 5kg"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Entre 5kg e 10kg"
                        });
                });

            modelBuilder.Entity("PostagemFacil.Solicitacoes.API.Data.Models.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("EtiquetaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PesoLimiteId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TipoCaixaId")
                        .HasColumnType("int");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PesoLimiteId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TipoCaixaId");

                    b.HasIndex("TransportadoraId");

                    b.ToTable("Solictacoes");
                });

            modelBuilder.Entity("PostagemFacil.Solicitacoes.API.Data.Models.StatusSolicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusSolicitacao");
                });

            modelBuilder.Entity("PostagemFacil.Solicitacoes.API.Data.Models.TipoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoCaixa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "20cm x 20cm x 20cm"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "40cm x 40cm x 40cm"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "60cm x 60cm x 60cm"
                        });
                });

            modelBuilder.Entity("PostagemFacil.Solicitacoes.API.Data.Models.Transportadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transportadora");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Correios"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "JadLog"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "DHL"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Fedex"
                        });
                });

            modelBuilder.Entity("PostagemFacil.Solicitacoes.API.Data.Models.Solicitacao", b =>
                {
                    b.HasOne("PostagemFacil.Solicitacoes.API.Data.Models.PesoLimite", "PesoLimite")
                        .WithMany()
                        .HasForeignKey("PesoLimiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostagemFacil.Solicitacoes.API.Data.Models.StatusSolicitacao", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostagemFacil.Solicitacoes.API.Data.Models.TipoCaixa", "TipoCaixa")
                        .WithMany()
                        .HasForeignKey("TipoCaixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostagemFacil.Solicitacoes.API.Data.Models.Transportadora", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PesoLimite");

                    b.Navigation("Status");

                    b.Navigation("TipoCaixa");

                    b.Navigation("Transportadora");
                });
#pragma warning restore 612, 618
        }
    }
}
